apiVersion: v2
version: 2.0.7
name: ingressh
description: SSH ingress for Kubernetes
appVersion: "v0.1.0-alpha"
type: application
keywords:
  - ingress
  - ssh
home: https://github.com/Kooper/IngreSsh
# icon:
sources:
  - https://github.com/Kooper/IngreSsh
maintainers:
  - name: Kooper
    url: https://github.com/Kooper
kubeVersion: ^1.23.0-0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: ^2.20.5
    tags:
      - bitnami-common
annotations:
  artifacthub.io/license: Apache-2.0
