---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/part-of: ingressh
  name: ingressh-role
rules:

- apiGroups:
  - ingress.kuberstein.io
  resources:
  - ingresshes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - ingress.kuberstein.io
  resources:
  - ingresshes/finalizers
  verbs:
  - update
- apiGroups:
  - ingress.kuberstein.io
  resources:
  - ingresshes/status
  verbs:
  - get
  - patch
  - update

- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list

- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
  - attach
  - exec

- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
  - get
