---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/part-of: ingressh
  name: ssh-config
data:
  server_config.yaml: |
    bind_address: ":30022"
    host_key_file: "/secret/ssh-privatekey"
    debug_image: "ubuntu"
