---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/part-of: ingressh
  name: ssh-secret
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3...
    -----END OPENSSH PRIVATE KEY-----
