# permissions for end users to edit ingresshes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ingressh-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ingressh
    app.kubernetes.io/part-of: ingressh
    app.kubernetes.io/managed-by: kustomize
  name: ingressh-editor-role
rules:
- apiGroups:
  - ingress.kuberstein.io
  resources:
  - ingresshes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ingress.kuberstein.io
  resources:
  - ingresshes/status
  verbs:
  - get
