---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ingress.kuberstein.io
  resources:
  - ingresshes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ingress.kuberstein.io
  resources:
  - ingresshes/finalizers
  verbs:
  - update
- apiGroups:
  - ingress.kuberstein.io
  resources:
  - ingresshes/status
  verbs:
  - get
  - patch
  - update
