apiVersion: ingress.kuberstein.io/v1
kind: IngreSsh
metadata:
  labels:
    app.kubernetes.io/name: ingressh
    app.kubernetes.io/instance: ingressh-sample
    app.kubernetes.io/part-of: ingressh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ingressh
  name: ingressh-sample
spec:
  image: busybox
  selector: app=nginx
  users:
  - name: kooper
    secretName: koopers-authorized-keys
