---
apiVersion: ingress.kuberstein.io/v1
kind: IngreSsh
metadata:
  name: ingressh-exec
spec:
  session: Exec
  command:
  - /bin/sh
  selectors:
  - app=nginx
  authorizedKeys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC94xuzqAmMS3UhZok6bi+IJ6M4XOF8amZJzRZBDLG8pnxQnqihL99AiryQGomjnn5G9tp7AjHup2MsyPjDEABAi51ULcEgFriYE2+KRuxT/6xvP3JT7SkEcXXfRR/FmRrjyQgxQurG87rlIvwXp8DvNcWJN4rfikXA53vhENfe7HLEN/rpXMRZXvyVXcMabjhJTWCO7l64gkwEfK2qXQDuxNlAhgPwjVoFvJNopNJ5uM/0wodqdYjNfTR9kF0Pm2E+ON5MGWx8kEQd72hO0gKC+i+pj4yYQQtfStfzrewU1aVtRKXRtRENSSxmJXmXqlyh2gCbIgIYrfGWN5MJkBIr
