{{- if not .Values.ingressh.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.secrets.name" (dict "defaultNameSuffix" "privatekey" "context" $) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: kubernetes.io/ssh-auth
data:
  {{- if .Values.ingressh.sshPrivateKey }}
  ssh-privatekey: {{ .Values.ingressh.sshPrivateKey | b64enc | quote }}
  {{- else }}
  ssh-privatekey: {{ genPrivateKey "ecdsa" | b64enc | quote }}
  {{- end }}
{{- end }}
